---
title: "milestone 2"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(skimr)
library(ggplot2)
library(tidyverse)
```

```{r Load Data}
survey <- read.csv("https://raw.githubusercontent.com/themarshallproject/incarcerated_survey/master/data/incarcerated_survey_responses-marshallproject_slate-march_2019.csv")
```

```{r Clean Data}
# Cleaning the data

# Renaming political party variables.
survey$party <- gsub("The Republican party", "Conservative", survey$party)
survey$party <- gsub("The Democratic party", "Liberal", survey$party)

# Turning the responses of the "stance on" questions into factor variables
stance_cols <- c("stance_on_assault_weapons_ban", "stance_on_marijuana_legalization", "stance_on_raise_min_wage", "stance_on_tightening_border_security")
survey[stance_cols] <- lapply(survey[stance_cols], factor)

levels(survey[stance_cols]) <- c("Undecided", "Strongly Oppose", "Oppose", "Support", "Strongly Support")
```

```{r Summarize Stance}
#Summarizing the explanatory and response variables using tidyverse.
survey_subset <- survey %>%
  select(party, 
         length_in_this_facility,
         stance_on_assault_weapons_ban, 
         stance_on_marijuana_legalization, 
         stance_on_tightening_border_security, 
         stance_on_raise_min_wage) %>%
  drop_na()

survey_subset %>%
  summary()
```

```{r party-length tables}
# Creating summary tables of party and survey length.
party_length_table <- table(survey$party, survey$length_in_this_facility)
knitr::kable(party_length_table, digits = 4, caption = "Political Party of Prisoners Based on Jail Time")

prop.table(table(survey$party, survey$length_in_this_facility))
```


# Weapons

```{r Weapons-Length Table}
# Table with weapons stance and length in facility
weptab <- table(survey_subset$stance_on_assault_weapons_ban, survey_subset$length_in_this_facility)
knitr::kable(weptab, digits = 4, caption = "Stance on Assault Weapons Ban Based on Jail Time")

prop.table(table(survey_subset$stance_on_assault_weapons_ban, survey_subset$length_in_this_facility))

# Plot of weapons stance and length
barplot(weptab, 
        col=c("lightblue1","steelblue2", "steelblue3", "steelblue4", "navy"), 
        legend = rownames(weptab),
        main = "Stance on Assault Weapon Bans",
        ylab = "Count",
        beside=TRUE)
```

```{r WeaponScale}
# Changing the stance factors to a scale from 0 to 1, with 0 being stronly oppose and 1 being strongly support.
survey$weapon_stance[survey$stance_on_assault_weapons_ban == "Strongly Oppose"] <- 0
survey$weapon_stance[survey$stance_on_assault_weapons_ban == "Oppose"] <- 0.25
survey$weapon_stance[survey$stance_on_assault_weapons_ban == "Undecided"] <- 0.5
survey$weapon_stance[survey$stance_on_assault_weapons_ban == "Support"] <- 0.75
survey$weapon_stance[survey$stance_on_assault_weapons_ban == "Strongly support"] <- 1

# Average stance on 0 to 1.
mean(survey$weapon_stance, na.rm = TRUE)
```

```{r WeaponBoxplot}
boxplot(survey$weapon_stance ~ survey$length_in_this_facility,
        main = "Assault Weapon Ban Stance on 0-1 Scale (where 1 is Strongly Support)")
```


# Marijuana Legalization

```{r Marijuana-Length Table}
# Table with weapons stance and length in facility
mjtab <- table(survey_subset$stance_on_marijuana_legalization, survey_subset$length_in_this_facility)
knitr::kable(mjtab, digits = 4, caption = "Stance on Marijuana Legalization Based on Jail Time")

prop.table(table(survey_subset$stance_on_marijuana_legalization, survey_subset$length_in_this_facility))

# Plot of weapons stance and length
barplot(mjtab, 
        col=c("lightblue1","steelblue2", "steelblue3", "steelblue4", "navy"), 
        legend = rownames(mjtab),
        main = "Stance on Marijuana Legalization",
        ylab = "Count",
        beside=TRUE)
```

```{r MarijuanaWeights}
# Adding weights to the factors of marijuana stance
survey$marijuana_stance[survey$stance_on_marijuana_legalization == "Oppose"] <- 0
survey$marijuana_stance[survey$stance_on_marijuana_legalization =="Strongly oppose"] <- 0.25
survey$marijuana_stance[survey$stance_on_marijuana_legalization =="Undecided"] <- 0.5
survey$marijuana_stance[survey$stance_on_marijuana_legalization == "Support"] <- 0.75
survey$marijuana_stance[survey$stance_on_marijuana_legalization == "Strongly support"] <- 1

# Average stance on 0 to 1.
mean(survey$marijuana_stance, na.rm = TRUE)
```

```{r MarijuanaBoxplot}
boxplot(survey$marijuana_stance ~ survey$length_in_this_facility,
        main = "Marijuana Legalization Stance on 0-1 Scale (where 1 is Strongly Support)")
```


# Border Security

```{r Border-Length Table}
# Table with weapons stance and length in facility
bstab <- table(survey_subset$stance_on_tightening_border_security, survey_subset$length_in_this_facility)
knitr::kable(bstab, digits = 4, caption = "Stance on Border Security Based on Jail Time")

prop.table(table(survey_subset$stance_on_tightening_border_security, survey_subset$length_in_this_facility))

# Plot of weapons stance and length
barplot(bstab, 
        col=c("lightblue1","steelblue2", "steelblue3", "steelblue4", "navy"), 
        legend = rownames(bstab),
        main = "Stance on Tightening Border Security",
        ylab = "Count",
        beside=TRUE)
```

```{r BorderWeights}
# Adding weights to the factors of marijuana stance
survey$border_stance[survey$stance_on_tightening_border_security == "Oppose"] <- 0
survey$border_stance[survey$stance_on_tightening_border_security =="Strongly oppose"] <- 0.25
survey$border_stance[survey$stance_on_tightening_border_security =="Undecided"] <- 0.5
survey$border_stance[survey$stance_on_tightening_border_security == "Support"] <- 0.75
survey$border_stance[survey$stance_on_tightening_border_security == "Strongly support"] <- 1

# Average stance on 0 to 1.
mean(survey$border_stance, na.rm = TRUE)
```

```{r BorderBoxplot}
boxplot(survey$border_stance ~ survey$length_in_this_facility,
        main = "Stance On Tightening Border Security on 0-1 Scale (where 1 is Strongly Support)")
```


# Minimum Wage

```{r MW-Length Table}
# Table with weapons stance and length in facility
mwtab <- table(survey_subset$stance_on_raise_min_wage, survey_subset$length_in_this_facility)
knitr::kable(mwtab, digits = 4, caption = "Stance on Raising Minumum Wage Based on Jail Time")

prop.table(table(survey_subset$stance_on_raise_min_wage, survey_subset$length_in_this_facility))

# Plot of weapons stance and length
barplot(mwtab, 
        col=c("lightblue1","steelblue2", "steelblue3", "steelblue4", "navy"), 
        legend = rownames(mwtab),
        main = "Stance on Raising the Minimum Wage",
        ylab = "Count",
        beside=TRUE)
```

```{r MinWageWeights}
# Adding weights to the factors of marijuana stance
survey$mw_stance[survey$stance_on_raise_min_wage == "Oppose"] <- 0
survey$mw_stance[survey$stance_on_raise_min_wage =="Strongly oppose"] <- 0.25
survey$mw_stance[survey$stance_on_raise_min_wage =="Undecided"] <- 0.5
survey$mw_stance[survey$stance_on_raise_min_wage == "Support"] <- 0.75
survey$mw_stance[survey$stance_on_raise_min_wage == "Strongly support"] <- 1

# Average stance on 0 to 1.
mean(survey$mw_stance, na.rm = TRUE)
```

```{r MWBoxplot}
boxplot(survey$mw_stance ~ survey$length_in_this_facility,
        main = "Stance On Raising the Minimum Wage on 0-1 Scale (where 1 is Strongly Support)")
```


# Mean of Four Political Views (Arms Stance, Marijuana Legalization, Border Security, and Minimum Wage)

-----
## creating variable in the data frame with NA on mean of political attitudes
## the higher the mean, the more liberal the prisoner
survey$mean_four_political_views <- (survey$weapon_stance + survey$marijuana_stance + survey$border_stance + survey$mw_stance) / 4

meanpolview_length_table <- table(survey$mean_four_political_views, survey$length_in_this_facility)
knitr::kable(meanpolview_length_table, digits = 4, caption = "Average Political Stance Based on Jail Time")

meanpolview_length_prop_table <- prop.table(table(survey$mean_four_political_views, survey$length_in_this_facility))

plot(meanpolview_length_table)

## creating variable in the data frame with no NA on mean of political attitudes
survey_subset$mean_four_political_views <- (survey_subset$weapon_stance + survey_subset$marijuana_stance + survey_subset$border_stance + survey_subset$mw_stance) / 4
meanpolview_length_table_no_NA <- table(survey_subset$mean_four_political_views, survey_subset$length_in_this_facility)
knitr::kable(meanpolview_length_table_no_NA, digits = 4, caption = "Average Political Stance Based on Jail Time (no NA)")
meanpolview_length_prop_table_no_NA <- prop.table(table(survey_subset$mean_four_political_views, survey_subset$length_in_this_facility))
plot(meanpolview_length_prop_table_no_NA)

## creating new political ideology variable with NA
survey$ideology[survey$mean_four_political_views == 1] <- "Very liberal"
survey$ideology[(survey$mean_four_political_views > 0) & (survey$mean_four_political_views < 1)] <- "Liberal"
survey$ideology[survey$mean_four_political_views == 0] <- "Politically neutral"
survey$ideology[(survey$mean_four_political_views < 0) & (survey$mean_four_political_views > -1)] <- "Conservative"
survey$ideology[survey$mean_four_political_views == -1] <- "Very conservative"

ideology_length_table <- table(survey$ideology, survey$length_in_this_facility)

knitr::kable(ideology_length_table, digits = 4, caption = "Average Political Ideology Based on Jail Time")
ideology_length_prop_table <- prop.table(table(survey$ideology, survey$length_in_this_facility))
plot(ideology_length_table)

## creating new political ideology variable with no NA
survey_no_NA$ideology[survey_no_NA$mean_four_political_views == 1] <- "Very liberal"
survey_no_NA$ideology[(survey_no_NA$mean_four_political_views > 0) & (survey_no_NA$mean_four_political_views < 1)] <- "Liberal"
survey_no_NA$ideology[survey_no_NA$mean_four_political_views == 0] <- "Politically neutral"
survey_no_NA$ideology[(survey_no_NA$mean_four_political_views < 0) & (survey_no_NA$mean_four_political_views > -1)] <- "Conservative"
survey_no_NA$ideology[survey_no_NA$mean_four_political_views == -1] <- "Very conservative"
ideology_and_facility_length_table_no_NA <- table(survey_no_NA$ideology, survey_no_NA$length_in_this_facility)
knitr::kable(ideology_and_facility_length_table_no_NA, digits = 4, caption = "Average Political Ideology Based on Jail Time (no NA)")
ideology_and_facility_length_prop_table_no_NA <- prop.table(table(survey_no_NA$ideology, survey_no_NA$length_in_this_facility))
 
plot(ideology_and_facility_length_table_no_NA)
----

## Regression

----
## linear regression model comparing the mean of four political views and the length of time spent in prison with NA
mean_four_political_views_and_facility_length_fit <- lm(survey$mean_four_political_views ~ survey$length_in_this_facility)
mean_four_political_views_and_facility_length_fit
mean_four_political_views_and_facility_length_fit_plot <- plot(mean_four_political_views_and_facility_length_fit) 
mean_four_political_views_and_facility_length_fit_r_squared <- summary(mean_four_political_views_and_facility_length_fit)$r.squared
mean_four_political_views_and_facility_length_fit_r_squared
## linear regression model comparing the mean of four political views and the length of time spent in prison with no NA
mean_four_political_views_and_facility_length_fit_no_NA <- lm(survey_no_NA$mean_four_political_views ~ survey_no_NA$length_in_this_facility)
mean_four_political_views_and_facility_length_fit_no_NA
mean_four_political_views_and_facility_length_fit_no_NA_plot <- plot(mean_four_political_views_and_facility_length_fit_no_NA) 
mean_four_political_views_and_facility_length_fit__no_NA_r_squared <- summary(mean_four_political_views_and_facility_length_fit_no_NA)$r.squared
mean_four_political_views_and_facility_length_fit__no_NA_r_squared
----







